name: Publish to Maven Central
on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish Package
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          OSSH_USERNAME: ${{ secrets.OSSH_USERNAME }}
          OSSH_PASSWORD: ${{ secrets.OSSH_PASSWORD }}
          OSSH_GPG_KEY_ID: ${{ secrets.OSSH_GPG_KEY_ID }}
          OSSH_GPG_SIGNING_KEY: ${{ secrets.OSSH_GPG_SIGNING_KEY }}
          OSSH_GPG_PASSPHRASE: ${{ secrets.OSSH_GPG_PASSPHRASE }}
