name: run-tests
on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: setup gradle
        uses: gradle/gradle-build-action@v2

      - name: build project
        run: ./gradlew build -x test

      - name: run tests
        run: ./gradlew test

      - name: publish test results
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
